#!/usr/bin/env node
/* ══════════════════════════════════════════════════════════════════
   runtime/tools/derive-digest.mjs

   Runs runtime/derive.js FOR REAL — samplePalette, fibreTile and the
   dominant-colour census — inside Chromium over http://, where the
   canvas is not tainted, and writes the result to
   runtime/specs/hokusai.digest.js.

   The offline test page reads that digest when a file:// origin refuses
   getImageData; over http the same code path derives live. Nothing in
   the digest is hand-written: every hex here came out of the function
   the extension will call.

     node runtime/tools/derive-digest.mjs
   ══════════════════════════════════════════════════════════════════ */
import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const TYPES = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.woff2': 'font/woff2', '.ndjson': 'text/plain' };

const server = createServer(async (req, res) => {
  const p = join(ROOT, decodeURIComponent(req.url.split('?')[0]));
  try {
    const buf = await readFile(p);
    res.writeHead(200, { 'content-type': TYPES[extname(p)] || 'application/octet-stream' });
    res.end(buf);
  } catch (e) { res.writeHead(404); res.end('nope'); }
});
await new Promise((r) => server.listen(0, r));
const port = server.address().port;

const SAMPLE = { ref: 'img:15', args: 'img:15@x0-96,y288-384', x: 0, y: 288, w: 96, h: 96 };

const browser = await chromium.launch({ executablePath: process.env.KW_CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('pageerror', (e) => console.error('[pageerror]', e.message));
await page.goto(`http://127.0.0.1:${port}/runtime/tools/digest-host.html`, { waitUntil: 'load' });
const digest = await page.evaluate(async (S) => window.__derive(S), SAMPLE);
await browser.close();
server.close();

const out = `/* GENERATED by runtime/tools/derive-digest.mjs — the output of
   runtime/derive.js executed over http, where the canvas is not tainted.
   The offline page reads this when a file:// origin refuses getImageData. */
window.KW_DIGEST = ${JSON.stringify(digest)};
`;
await writeFile(resolve(HERE, '../specs/hokusai.digest.js'), out);
console.log('ground', digest.ground, '· σ', digest.sigma, '· tile', (digest.tile || '').length, 'chars');
console.log(digest.provenance);
